### ISSUE TITLE
[1.12.2] Incompatibility with all mods/plugins using newer Mixin version

### ISSUE THREAD

**Issue by Brycey92** [satyrnidae/wolfarmor#104]
**Issue Description**
When I run the latest version of the mod for 1.12.2 with other mods that are maintained and using Mixin 0.8, the discrepancy in Mixin dependencies causes a crash.

**Reproduction Steps**
1. Find and install a mod using Mixin 0.8
2. Install Wolf Armor
3. Launch the game
4. Observe crash

**Expected Behavior**
The mod should be compiled with Mixin 0.8.

**Version Information:**
 - OS: Windows 7
 - Java: Java 8
 - Minecraft Version: 1.12.2
 - Mod Version: 1.12.2-3.4.1.1-universal

**Comment by satyrnidae** [comment]
Fixed by 3c022829018b1060db7fb3f92617fb83295690d1 in v3.5.4 and higher.
