### ISSUE TITLE
[1.12] [Duplicate] Strange/Unexpected Behavior When Removing A Chest From a Wolf

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [satyrnidae/wolfarmor#166]
**Issue Description**
Storing items in the wolf's chest then removing the chest will not drop the items that were stored in the chest. It saves that information for when the chest is put back on the wolf. I mean, it doesn't delete the items so that is a plus but that is very weird behavior and not how it should logically behave. Players would likely think it deleted their items (as I did at first) and if they have a lot of dogs it would be very easy to mix up which to put the chest back on - even if they knew about this feature. Furthermore, it basically acts as a way to 'hide' items from other people (including staff of a server) which is problematic. 

**Reproduction Steps**
1. Tame a wolf.
2. Place a chest on the wolf.
3. Store items in the chest.
4. Open the wolf's inventory and click the "Remove Chest" button.
5. Watch as it only drops the chest and not the items.
6. Open the wolf's inventory to confirm that there are no items stored there (because it has no chest on it).
7. Put the same chest back on the wolf and open the wolf's inventory. 
8. Stare in confusion when the items are magically back in the storage of the wolf. :P  

**Expected Behavior**
When the player removes the chest from the wolf I'd expect it to drop the items that were being stored in the chest.

**Screenshots / Videos**
GIF: https://gyazo.com/c5d96c66d2e1b4142d9765d9e33d846b

**Version Information:**
 - OS: Windows 10
 - Java: Java 8 Update 251 (64-bit) also Java SE Development Kit 8 Update 221 (64-bit)
 - Minecraft Version: Forge 1.12.2
 - Forge Version: forge-14.23.5.2847
 - Mod Version: wolfarmor-1.12.2-3.7.1-universal-signed.jar

**Additional Context**
- I do have Quark installed but I disabled Quark's petting feature so it doesn't conflict with opening the dog's inventory. Also I am testing this in singleplayer before I add the mod to my serverpack and use it on a server.
- As a side note, killing the wolf while the chest is on (or off of) the wolf DOES drop the items.

Hope this gets fixed! Awesome mod other than this issue! :)

**Comment by satyrnidae** [comment]
Fixed this in #160, but I guess i haven't released that version yet, oops

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> Fixed this in #160, but I guess i haven't released that version yet, oops

Ah okay. Thanks!
