### ISSUE TITLE
FTB Crash Exit code 0 

### ISSUE THREAD

**Issue by StryenGHG** [satyrnidae/wolfarmor#176]
Hey,

so first of all excuse me for my bad english.
I installed everything the right way but everytime i start any mod pack from the ftb launcher my minecraft just crashes and says Exit code : 0. In change log it says exit code 1.
Tryed everything uninstalled ftb, minecraft, java even tryed going in to %temp% and deleting everything those programms installed there. still not working. I dont know if this is a problem with mc it selfe or the ftb launcher but i hope you guys can help me out so i can play with my friends.

Thanks
![Screenshot (9)](https://user-images.githubusercontent.com/76783374/103361350-78249280-4ab9-11eb-979d-e92673d0c8f7.png)
![Screenshot (7)](https://user-images.githubusercontent.com/76783374/103361360-7955bf80-4ab9-11eb-9b8b-b01b72a99e27.png)
![Screenshot (8)](https://user-images.githubusercontent.com/76783374/103361366-7955bf80-4ab9-11eb-9c49-0b00d1f12f5f.png)

**Comment by satyrnidae** [comment]
duplicates #165
