### ISSUE TITLE
Wolf armor set produces double the protection

### ISSUE THREAD

**Issue by alanESV2** [satyrnidae/wolfarmor#202]
The wolf pelt armor items, when all worn, are giving me 22 armor even though when you hover over the items it only adds up to 11 armor.

![2022-04-27_23 32 13](https://user-images.githubusercontent.com/49703317/165671040-7a7bd770-2712-47c9-b168-3aaa3f1703f3.png)
![2022-04-27_23 32 31](https://user-images.githubusercontent.com/49703317/165671050-bd52aeeb-1ffc-489d-bacc-28233c957cfe.png)
.

**Comment by satyrnidae** [comment]
Unfortunately, that's not part of this mod; the only items added here are armor sets specifically for wolves to wear. You should report this to PrimalCore instead.
