### ISSUE TITLE
There should be a config option in the renderer to be able to make wolf heads smaller

### ISSUE THREAD

**Issue by TheRPGAdventurer** [satyrnidae/wolfarmor#72]
**Is your feature request related to a problem? Please describe.**
I hate how big the wolf heads are when theyre babies, WE cant see the collar and makes me hate them than the intended way of "making them cute" make it a config sso people can enable and disable. 

**Describe the solution you'd like**
You can do this by making a custom renderer (i made one tell me if youre interested) and register them like an entity, it will override the vanilla renderer.

**Comment by satyrnidae** [comment]
Hi, I'm not sure this feature is a good fit for this mod, especially considering the baby wolves do not have any of the new functionality introduced to the adult wolves.  However, I will consider supporting any mod that enables this new functionality! 
Thanks for the suggestion!
