### ISSUE TITLE
[Compatibility] BetterAnimationsCollection 2

### ISSUE THREAD

**Issue by satyrnidae** [satyrnidae/wolfarmor#77]
Determine if this mod can be made compatible

**Comment by J-Raffoul** [comment]
I'm getting this crash-report when running these two mods

[crash-2020-01-08_14.12.44-client.txt](https://github.com/satyrnidae/wolfarmor/files/4033478/crash-2020-01-08_14.12.44-client.txt)

**Comment by satyrnidae** [comment]
The crash should be fixed now

**Comment by satyrnidae** [comment]
Will not be implementing new animations for now.
