### ISSUE TITLE
right click with Quark chests

### ISSUE THREAD

**Issue by Rotzo** [satyrnidae/wolfarmor#78]
hi. thanks for your awesome mod :)

i got this small issue: i tried to use one of quarks wooden chests to add an inventory to my wolf, but it didn't work. it was only doable with a vanilla chest. i've seen that there was a report about this that's closed now, but it still don't seem to work for me.

cheers

**Comment by satyrnidae** [comment]
I tested this w/ Quark against the latest build of the mod; it looks like this is indeed an issue.  Thanks for the heads up! I'll add this to the v3 release project.
