### ISSUE TITLE
[1.12] config option to remove crafting recipie

### ISSUE THREAD

**Issue by SpGilbert** [satyrnidae/wolfarmor#83]
Could you make an option to disable crafting recipes for crafting the wolf armor?

**Comment by satyrnidae** [comment]
- [ ] Add new config setting, requires Minecraft restart
- [ ] Create new factory type to check new config setting and conditionally load recipes
- [ ] Implement new factory type condition on vanilla wolf armors

**Comment by satyrnidae** [comment]
Looks like I'm hitting an issue w/ advancements throwing errors when the recipes are disabled.  Amounts to log spam, but I don't know that the version of forge which I am developing against supports conditional advancements. Will try updating forge, but releasing a snapshot build in the meantime.
