### ISSUE TITLE
Better Animal Models Support

### ISSUE THREAD

**Issue by IdrisQe** [satyrnidae/wolfarmor#84]
Wolf Armor has compatability with Sophisticated Wolves, Better Animal Models has compatability with Sophisticated Wolves, the only thing that would be needed to complete an amazing wolf trifecta is for Wolf Armor to be made compatible with the updated models from Better Animal Models. I understand this would be a lot of work, but I asked in Better Animal Models https://github.com/cybercat5555/BetterAnimals/issues/19 and was told it'd be too much work on their end. I'm wondering if it'd be easier for you?

**Comment by satyrnidae** [comment]
This one would likely require more or less an equivalent amount of code reproduction on my end.  I can look into it later when it's easier to swap out models, but at this time, I have settled for simply making sure that it doesn't crash on load.
