### ISSUE TITLE
Better Animals Plus - Crash on Startup

### ISSUE THREAD

**Issue by Sarund9** [satyrnidae/wolfarmor#85]
Incompatibility with Better Animals Plus.
Crash report says something about Class Cast Exeption.
Probably because better Animals Plus adds a Completely new wolf apparently.
Crashes on Load.

java.lang.ClassCastException: com.ocelot.betteranimals.client.render.entity.RenderNewWolf cannot be cast to net.minecraft.client.renderer.entity.RenderWolf
Full crash report: https://paste.dimdev.org/dafowesaba.mccrash

Better Animals Plus: https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus

This happened on Windows 7

**Comment by satyrnidae** [comment]
duplicates #84 because same root cause
