### ISSUE TITLE
[1.12] Compatibility problem with Let Sleeping Dogs Lie

### ISSUE THREAD

**Issue by fkrisi11** [satyrnidae/wolfarmor#87]
**Issue Description**
Wolf's armor doesn't adjust to the laying position of the wolves that Let Sleeping Dogs Lie provides

**Relevant Mods**
https://www.curseforge.com/minecraft/mc-mods/let-sleeping-dogs-lie

**Reproduction Steps**
1. Tame a wolf
2. Put armor on it (and maybe even a chest)
3. Make the dog sit
4. Wait 10-15 seconds while you are like 10 blocks away from the wolf
5. As the wolf lays down, you will see that the armor doesn't adjust to its laying position

**Expected Behavior**
Armor adjusts to the wolf's laying position

**Screenshots / Videos**
![bug](https://user-images.githubusercontent.com/26310365/79065567-9e976900-7cb1-11ea-94cd-5d4614ffab5b.jpg)

**Version Information:**
 - OS: Windows 10
 - Java: Java 8
 - Minecraft Version: 1.12
 - Mod Version: wolfarmor-1.12.2-2.2.3.1798-universal

**Comment by satyrnidae** [comment]
Need to improve my compatibility framework for this to work properly... a bit late rn but i'll work on that under #145
