### ISSUE TITLE
Old Mod Versions Unavailable on CurseForge

### ISSUE THREAD

**Issue by Charles445** [satyrnidae/wolfarmor#88]
The CurseForge downloads no longer include old versions of the mod.

This is a **huge** headache for modpacks that rely on this mod, as they cannot keep the same version of the mod in later updates if necessary.

For example, RLCraft uses wolfarmor-1.12.2-2.2.3.1798-universal, but that version of the mod is now missing from CurseForge.

Could you keep the old versions archived on CurseForge? It's very risky to use the mod in a pack when its old versions disappear.

**Comment by satyrnidae** [comment]
the versions are _archived_, but I'll make them public if that would help
